"""
GAUSS+DNA — Lista de moedas monitoradas e filtros do scanner dinâmico.
"""

# ── Watchlist prioritária — escaneada PRIMEIRO em todo ciclo ─────────────────
# Moedas do bubble pessoal do usuário: sempre na frente do top dinâmico
PRIORITY_WATCHLIST = [
    ("NEARUSDT",  "NEAR/USDT",  "NEAR"),
    ("HYPEUSDT",  "HYPE/USDT",  "HYPE"),
    ("TIAUSDT",   "TIA/USDT",   "TIA"),
    ("HBARUSDT",  "HBAR/USDT",  "HBAR"),
    ("ETHFIUSDT", "ETHFI/USDT", "ETHFI"),
    ("PENGUUSDT", "PENGU/USDT", "PENGU"),
    ("AGLDUSDT",  "AGLD/USDT",  "AGLD"),
    ("HOMEUSDT",  "HOME/USDT",  "HOME"),
    ("IRYSUSDT",  "IRYS/USDT",  "IRYS"),
    ("MLNUSDT",   "MLN/USDT",   "MLN"),
    ("ASTERUSDT", "ASTER/USDT", "ASTER"),
    ("ALLOUUSDT", "ALLOU/USDT", "ALLOU"),
    ("LTCUSDT",   "LTC/USDT",   "LTC"),
    ("PENDLEUSDT","PENDLE/USDT","PENDLE"),
    ("OPENUSDT",  "OPEN/USDT",  "OPEN"),
    ("HUSDT",     "H/USDT",     "H"),
    ("SUIUSDT",   "SUI/USDT",   "SUI"),
    ("ETHUSDT",   "ETH/USDT",   "ETH"),
    ("BTCUSDT",   "BTC/USDT",   "BTC"),
    ("XMRUSDT",   "XMR/USDT",   "XMR"),
    ("HMSTRUSDT", "HMSTR/USDT", "HMSTR"),
    ("TRUMPUSDT", "TRUMP/USDT", "TRUMP"),
    ("BNBUSDT",   "BNB/USDT",   "BNB"),
    ("ADAUSDT",   "ADA/USDT",   "ADA"),
    ("SOLUSDT",   "SOL/USDT",   "SOL"),
    ("EPICUSDT",  "EPIC/USDT",  "EPIC"),
    ("RAINUSDT",  "RAIN/USDT",  "RAIN"),
    ("IOUSDT",    "IO/USDT",    "IO"),
    ("BCHUSDT",   "BCH/USDT",   "BCH"),
    ("ZECUSDT",   "ZEC/USDT",   "ZEC"),
    ("GRASSUSDT", "GRASS/USDT", "GRASS"),
    ("CVXUSDT",   "CVX/USDT",   "CVX"),
    ("LDOUSDT",   "LDO/USDT",   "LDO"),
    ("XTZUSDT",   "XTZ/USDT",   "XTZ"),
    ("GLMUSDT",   "GLM/USDT",   "GLM"),
]

# Stablecoins, tokens alavancados e moedas com backtest ruim — excluídos do scanner dinâmico
_EXCLUIR = {
    "USDC", "BUSD", "TUSD", "FDUSD", "DAI", "USDP", "PAXG", "WBTC", "WETH",
    "EUR", "GBP", "BRL", "UST", "USDD", "FRAX", "USD1", "USDE", "USDT0",
    "AIXDROP",
    "GIGGLE", "USELESS", "EDEN", "PLAY", "MAGMA", "CHIP",
    "SLX", "JGGL", "MYX", "SENTIS", "XPL", "TAO",
}
_EXCLUIR_SUFIXO = ("UP", "DOWN", "BULL", "BEAR", "3L", "3S", "2L", "2S", "5L", "5S")

# Lista fixa de moedas monitoradas (usada quando DYNAMIC_SCAN=false)
COINS = [
    # ── Mega caps ────────────────────────────────────────────────────────────
    ("BTCUSDT","BTC/USDT","BTC"), ("ETHUSDT","ETH/USDT","ETH"),
    ("BNBUSDT","BNB/USDT","BNB"), ("XRPUSDT","XRP/USDT","XRP"),
    ("TRXUSDT","TRX/USDT","TRX"), ("ADAUSDT","ADA/USDT","ADA"),
    # ── L1 — alta volatilidade e tendências limpas ────────────────────────
    ("SOLUSDT","SOL/USDT","SOL"), ("AVAXUSDT","AVAX/USDT","AVAX"),
    ("SUIUSDT","SUI/USDT","SUI"), ("APTUSDT","APT/USDT","APT"),
    ("NEARUSDT","NEAR/USDT","NEAR"), ("TONUSDT","TON/USDT","TON"),
    ("SEIUSDT","SEI/USDT","SEI"), ("TIAUSDT","TIA/USDT","TIA"),
    ("ALGOUSDT","ALGO/USDT","ALGO"), ("VETUSDT","VET/USDT","VET"),
    ("HBARUSDT","HBAR/USDT","HBAR"), ("STXUSDT","STX/USDT","STX"),
    ("ICPUSDT","ICP/USDT","ICP"), ("XLMUSDT","XLM/USDT","XLM"),
    ("KASUSDT","KAS/USDT","KAS"), ("EGLDUSDT","EGLD/USDT","EGLD"),
    ("FLOWUSDT","FLOW/USDT","FLOW"), ("CFXUSDT","CFX/USDT","CFX"),
    # ── DeFi / infraestrutura ─────────────────────────────────────────────
    ("LINKUSDT","LINK/USDT","LINK"), ("INJUSDT","INJ/USDT","INJ"),
    ("JUPUSDT","JUP/USDT","JUP"), ("ARBUSDT","ARB/USDT","ARB"),
    ("OPUSDT","OP/USDT","OP"), ("UNIUSDT","UNI/USDT","UNI"),
    ("AAVEUSDT","AAVE/USDT","AAVE"), ("ENAUSDT","ENA/USDT","ENA"),
    ("ONDOUSDT","ONDO/USDT","ONDO"), ("GRTUSDT","GRT/USDT","GRT"),
    ("LDOUSDT","LDO/USDT","LDO"), ("RUNEUSDT","RUNE/USDT","RUNE"),
    ("PENDLEUSDT","PENDLE/USDT","PENDLE"), ("CAKEUSDT","CAKE/USDT","CAKE"),
    ("CRVUSDT","CRV/USDT","CRV"), ("DYDXUSDT","DYDX/USDT","DYDX"),
    ("SNXUSDT","SNX/USDT","SNX"), ("GMXUSDT","GMX/USDT","GMX"),
    ("COMPUSDT","COMP/USDT","COMP"), ("STGUSDT","STG/USDT","STG"),
    # ── IA / narrativa ───────────────────────────────────────────────────
    ("FETUSDT","FET/USDT","FET"), ("TAOUSDT","TAO/USDT","TAO"),
    ("RENDERUSDT","RENDER/USDT","RENDER"), ("WLDUSDT","WLD/USDT","WLD"),
    ("IMXUSDT","IMX/USDT","IMX"), ("EIGENUSDT","EIGEN/USDT","EIGEN"),
    # ── Meme coins com alta liquidez ─────────────────────────────────────
    ("DOGEUSDT","DOGE/USDT","DOGE"), ("PEPEUSDT","PEPE/USDT","PEPE"),
    ("WIFUSDT","WIF/USDT","WIF"), ("SHIBUSDT","SHIB/USDT","SHIB"),
    ("FLOKIUSDT","FLOKI/USDT","FLOKI"), ("BONKUSDT","BONK/USDT","BONK"),
    ("NOTUSDT","NOT/USDT","NOT"), ("POPCATUSDT","POPCAT/USDT","POPCAT"),
    ("DOGSUSDT","DOGS/USDT","DOGS"), ("TURBOUSDT","TURBO/USDT","TURBO"),
    ("MEWUSDT","MEW/USDT","MEW"), ("BOMEUSDT","BOME/USDT","BOME"),
    # ── High beta estabelecidos ───────────────────────────────────────────
    ("DOTUSDT","DOT/USDT","DOT"), ("ATOMUSDT","ATOM/USDT","ATOM"),
    ("LTCUSDT","LTC/USDT","LTC"), ("FILUSDT","FIL/USDT","FIL"),
    ("ARUSDT","AR/USDT","AR"), ("BCHUSDT","BCH/USDT","BCH"),
    ("ETCUSDT","ETC/USDT","ETC"), ("XTZUSDT","XTZ/USDT","XTZ"),
    ("QNTUSDT","QNT/USDT","QNT"), ("BATUSDT","BAT/USDT","BAT"),
    # ── L2 / interoperabilidade ───────────────────────────────────────────
    ("STRKUSDT","STRK/USDT","STRK"), ("ZETAUSDT","ZETA/USDT","ZETA"),
    ("PYTHUSDT","PYTH/USDT","PYTH"), ("WUSDT","W/USDT","W"),
    ("ZKUSDT","ZK/USDT","ZK"), ("MNTUSDT","MNT/USDT","MNT"),
    ("ZROUSDT","ZRO/USDT","ZRO"), ("SAGAUSDT","SAGA/USDT","SAGA"),
    ("BLURUSDT","BLUR/USDT","BLUR"), ("ORDIUSDT","ORDI/USDT","ORDI"),
    # ── Gaming / metaverso ───────────────────────────────────────────────
    ("AXSUSDT","AXS/USDT","AXS"), ("SANDUSDT","SAND/USDT","SAND"),
    ("MANAUSDT","MANA/USDT","MANA"), ("GALAUSDT","GALA/USDT","GALA"),
    ("CHZUSDT","CHZ/USDT","CHZ"), ("APEUSDT","APE/USDT","APE"),
    ("YGGUSDT","YGG/USDT","YGG"), ("MAGICUSDT","MAGIC/USDT","MAGIC"),
    # ── DePIN / outros ───────────────────────────────────────────────────
    ("IOUSDT","IO/USDT","IO"), ("ROSEUSDT","ROSE/USDT","ROSE"),
    ("IOTXUSDT","IOTX/USDT","IOTX"), ("CELOUSDT","CELO/USDT","CELO"),
    ("JASMYUSDT","JASMY/USDT","JASMY"), ("LPTUSDT","LPT/USDT","LPT"),
    ("AEVOUSDT","AEVO/USDT","AEVO"), ("BERAUSDT","BERA/USDT","BERA"),
    ("LISTAUSDT","LISTA/USDT","LISTA"), ("REZUSDT","REZ/USDT","REZ"),
    # ── L1 adicionais ────────────────────────────────────────────────────
    ("FTMUSDT","FTM/USDT","FTM"), ("KAVAUSDT","KAVA/USDT","KAVA"),
    ("THETAUSDT","THETA/USDT","THETA"), ("ONTUSDT","ONT/USDT","ONT"),
    ("ZILLUSDT","ZIL/USDT","ZIL"), ("BANDUSDT","BAND/USDT","BAND"),
    ("IOTAUSDT","IOTA/USDT","IOTA"), ("MINAUSDT","MINA/USDT","MINA"),
    ("MANTAUSDT","MANTA/USDT","MANTA"), ("KSMUSDT","KSM/USDT","KSM"),
    ("QTUMUSDT","QTUM/USDT","QTUM"), ("WAVESUSDT","WAVES/USDT","WAVES"),
    ("IOSTUSDT","IOST/USDT","IOST"), ("NKNUSDT","NKN/USDT","NKN"),
    ("CTSIUSDT","CTSI/USDT","CTSI"), ("COTIUSDT","COTI/USDT","COTI"),
    ("LSKUSDT","LSK/USDT","LSK"), ("ZENUSDT","ZEN/USDT","ZEN"),
    ("POWRUSDT","POWR/USDT","POWR"), ("SCRTUSDT","SCRT/USDT","SCRT"),
    ("ACAUSDT","ACA/USDT","ACA"), ("POLUSDT","POL/USDT","POL"),
    ("CKBUSDT","CKB/USDT","CKB"), ("KLAYUSDT","KLAY/USDT","KLAY"),
    ("XDCUSDT","XDC/USDT","XDC"), ("NEOUSDT","NEO/USDT","NEO"),
    ("XEMUSDT","XEM/USDT","XEM"), ("WAXPUSDT","WAXP/USDT","WAXP"),
    ("HNTUSDT","HNT/USDT","HNT"), ("OSMUSDT","OSMO/USDT","OSMO"),
    # ── DeFi adicionais ──────────────────────────────────────────────────
    ("MKRUSDT","MKR/USDT","MKR"), ("SUSHIUSDT","SUSHI/USDT","SUSHI"),
    ("BALUSDT","BAL/USDT","BAL"), ("LRCUSDT","LRC/USDT","LRC"),
    ("ANKRUSDT","ANKR/USDT","ANKR"), ("CELRUSDT","CELR/USDT","CELR"),
    ("YFIUSDT","YFI/USDT","YFI"), ("OCEANUSDT","OCEAN/USDT","OCEAN"),
    ("KNCUSDT","KNC/USDT","KNC"), ("ZRXUSDT","ZRX/USDT","ZRX"),
    ("PERPUSDT","PERP/USDT","PERP"), ("RSRUSDT","RSR/USDT","RSR"),
    ("FXSUSDT","FXS/USDT","FXS"), ("ETHFIUSDT","ETHFI/USDT","ETHFI"),
    ("ALPACAUSDT","ALPACA/USDT","ALPACA"), ("REQUSDT","REQ/USDT","REQ"),
    ("OMUSDT","OM/USDT","OM"), ("ALICEUSDT","ALICE/USDT","ALICE"),
    ("SPELLUSDT","SPELL/USDT","SPELL"), ("RENUSDT","REN/USDT","REN"),
    ("CVXUSDT","CVX/USDT","CVX"), ("LITUSDT","LIT/USDT","LIT"),
    ("AMPUSDT","AMP/USDT","AMP"), ("OXTUSDT","OXT/USDT","OXT"),
    ("FORTHUSDT","FORTH/USDT","FORTH"), ("GLMUSDT","GLM/USDT","GLM"),
    ("AGLDUSDT","AGLD/USDT","AGLD"), ("RAREUSDT","RARE/USDT","RARE"),
    ("BONDUSDT","BOND/USDT","BOND"), ("WOOUSDT","WOO/USDT","WOO"),
    ("BNTUSDT","BNT/USDT","BNT"), ("LQTYUSDT","LQTY/USDT","LQTY"),
    # ── IA / dados adicionais ─────────────────────────────────────────────
    ("AGIXUSDT","AGIX/USDT","AGIX"), ("PHBUSDT","PHB/USDT","PHB"),
    ("ARKMUSDT","ARKM/USDT","ARKM"), ("NMRUSDT","NMR/USDT","NMR"),
    ("AIUSDT","AI/USDT","AI"), ("MOVRUSDT","MOVR/USDT","MOVR"),
    ("GLMRUSDT","GLMR/USDT","GLMR"), ("TRBUSDT","TRB/USDT","TRB"),
    ("ENSUSDT","ENS/USDT","ENS"), ("AUDIOUSDT","AUDIO/USDT","AUDIO"),
    ("RIFUSDT","RIF/USDT","RIF"), ("CTXCUSDT","CTXC/USDT","CTXC"),
    # ── L2 / Rollup adicionais ────────────────────────────────────────────
    ("METISUSDT","METIS/USDT","METIS"), ("ALTUSDT","ALT/USDT","ALT"),
    ("XAIUSDT","XAI/USDT","XAI"), ("DYMAUSDT","DYMA/USDT","DYMA"),
    ("BEAMUSDT","BEAM/USDT","BEAM"), ("POLYXUSDT","POLYX/USDT","POLYX"),
    ("STPTUSDT","STPT/USDT","STPT"), ("PORTAUSDT","PORTAL/USDT","PORTAL"),
    ("OMNIUSDT","OMNI/USDT","OMNI"), ("IDUSDT","ID/USDT","ID"),
    ("AXLUSDT","AXL/USDT","AXL"), ("SYNUSDT","SYN/USDT","SYN"),
    ("ASTRUSDT","ASTR/USDT","ASTR"), ("SXPUSDT","SXP/USDT","SXP"),
    # ── Gaming / NFT adicionais ───────────────────────────────────────────
    ("ILVUSDT","ILV/USDT","ILV"), ("RONUSDT","RON/USDT","RON"),
    ("PIXELUSDT","PIXEL/USDT","PIXEL"), ("MBOXUSDT","MBOX/USDT","MBOX"),
    ("SLPUSDT","SLP/USDT","SLP"), ("DARUSDT","DAR/USDT","DAR"),
    ("VOXELUSDT","VOXEL/USDT","VOXEL"), ("TLMUSDT","TLM/USDT","TLM"),
    ("NFPUSDT","NFP/USDT","NFP"), ("HIGHUSDT","HIGH/USDT","HIGH"),
    ("RDNTUSDT","RDNT/USDT","RDNT"), ("WINUSDT","WIN/USDT","WIN"),
    ("DEGOUSDT","DEGO/USDT","DEGO"), ("LAZIOUSDT","LAZIO/USDT","LAZIO"),
    ("SANTOSUSDT","SANTOS/USDT","SANTOS"), ("GMTUSDT","GMT/USDT","GMT"),
    ("ATMUSDT","ATM/USDT","ATM"), ("CITYUSDT","CITY/USDT","CITY"),
    # ── Meme / tendências ─────────────────────────────────────────────────
    ("TRUMPUSDT","TRUMP/USDT","TRUMP"), ("MOODENGUSDT","MOODENG/USDT","MOODENG"),
    ("NEIROUSDT","NEIRO/USDT","NEIRO"), ("BRETTUSDT","BRETT/USDT","BRETT"),
    ("CATIUSDT","CATI/USDT","CATI"), ("HMSTRUSDT","HMSTR/USDT","HMSTR"),
    ("ACTUSDT","ACT/USDT","ACT"), ("GOATUSDT","GOAT/USDT","GOAT"),
    ("PNUTUSDT","PNUT/USDT","PNUT"), ("COWUSDT","COW/USDT","COW"),
    ("GALUSDT","GAL/USDT","GAL"), ("OGNUSDT","OGN/USDT","OGN"),
    ("PEOPLEUSDT","PEOPLE/USDT","PEOPLE"), ("LUNCUSDT","LUNC/USDT","LUNC"),
    ("USTCUSDT","USTC/USDT","USTC"), ("ALPHAUSDT","ALPHA/USDT","ALPHA"),
    # ── Infra / DePIN adicionais ──────────────────────────────────────────
    ("STORJUSDT","STORJ/USDT","STORJ"), ("SCUSDT","SC/USDT","SC"),
    ("RVNUSDT","RVN/USDT","RVN"), ("HOTUSDT","HOT/USDT","HOT"),
    ("DUSKUSDT","DUSK/USDT","DUSK"), ("ENJUSDT","ENJ/USDT","ENJ"),
    ("NEXOUSDT","NEXO/USDT","NEXO"), ("TFUELUSDT","TFUEL/USDT","TFUEL"),
    ("SUNUSDT","SUN/USDT","SUN"), ("NULSUSDT","NULS/USDT","NULS"),
    ("FUNUSDT","FUN/USDT","FUN"), ("CVCUSDT","CVC/USDT","CVC"),
    ("TRUUSDT","TRU/USDT","TRU"), ("TWTUSDT","TWT/USDT","TWT"),
    ("DEXEUSDT","DEXE/USDT","DEXE"), ("HOOKUSDT","HOOK/USDT","HOOK"),
    ("MTLUSDT","MTL/USDT","MTL"), ("ACHUSDT","ACH/USDT","ACH"),
    ("PONDUSDT","POND/USDT","POND"), ("KEYUSDT","KEY/USDT","KEY"),
    # ── Narrativas emergentes ─────────────────────────────────────────────
    ("HYPEUSDT","HYPE/USDT","HYPE"), ("VIRTUALUSDT","VIRTUAL/USDT","VIRTUAL"),
    ("MOVEUSDT","MOVE/USDT","MOVE"), ("GRASSUSDT","GRASS/USDT","GRASS"),
    ("SOLVUSDT","SOLV/USDT","SOLV"), ("UXLINKUSDT","UXLINK/USDT","UXLINK"),
    ("KERNELUSDT","KERNEL/USDT","KERNEL"), ("MLNUSDT","MLN/USDT","MLN"),
    ("BANANAUSDT","BANANA/USDT","BANANA"), ("SPECUSDT","SPEC/USDT","SPEC"),
    # ── Alts médio cap ────────────────────────────────────────────────────
    ("ARPAUSDT","ARPA/USDT","ARPA"), ("STEEMUSDT","STEEM/USDT","STEEM"),
    ("SYSUSDT","SYS/USDT","SYS"), ("BAKEUSDT","BAKE/USDT","BAKE"),
    ("DODOUSDT","DODO/USDT","DODO"), ("WINGUSDT","WING/USDT","WING"),
    ("XVSUSDT","XVS/USDT","XVS"), ("SFPUSDT","SFP/USDT","SFP"),
    ("PROSUSDT","PROS/USDT","PROS"), ("HARDUSDT","HARD/USDT","HARD"),
    ("QUICKUSDT","QUICK/USDT","QUICK"), ("KDAUSDT","KDA/USDT","KDA"),
    ("BICOUSDT","BICO/USDT","BICO"), ("REEFUSDT","REEF/USDT","REEF"),
    ("EPXUSDT","EPX/USDT","EPX"), ("MBLUSDT","MBL/USDT","MBL"),
    ("ATAUSDT","ATA/USDT","ATA"), ("MULTIUSDT","MULTI/USDT","MULTI"),
    ("GTCUSDT","GTC/USDT","GTC"), ("HIVEUSDT","HIVE/USDT","HIVE"),
    ("RAYUSDT","RAY/USDT","RAY"), ("ORCAUSDT","ORCA/USDT","ORCA"),
    ("JITOUSDT","JITO/USDT","JITO"), ("WEMIXUSDT","WEMIX/USDT","WEMIX"),
    ("FIDAUSDT","FIDA/USDT","FIDA"), ("SWEATUSDT","SWEAT/USDT","SWEAT"),
    ("CLVUSDT","CLV/USDT","CLV"), ("UMAUSDT","UMA/USDT","UMA"),
    ("DIAUSDT","DIA/USDT","DIA"), ("LINAUSDT","LINA/USDT","LINA"),
    ("ORNUSDT","ORN/USDT","ORN"), ("IDEXUSDT","IDEX/USDT","IDEX"),
    ("TVKUSDT","TVK/USDT","TVK"), ("COSUSDT","COS/USDT","COS"),
    ("LTOUSDT","LTO/USDT","LTO"), ("KP3RUSDT","KP3R/USDT","KP3R"),
    ("MCUSDT","MC/USDT","MC"), ("ACMUSDT","ACM/USDT","ACM"),
    ("JUVUSDT","JUV/USDT","JUV"), ("FLMUSDT","FLM/USDT","FLM"),
    ("APEXUSDT","APEX/USDT","APEX"), ("BSVUSDT","BSV/USDT","BSV"),
    ("AMBUSDT","AMB/USDT","AMB"), ("HFTUSDT","HFT/USDT","HFT"),
    ("IRISUSDT","IRIS/USDT","IRIS"), ("MDXUSDT","MDX/USDT","MDX"),
    # ── Watchlist do usuário ──────────────────────────────────────────────
    ("IRYSUSDT","IRYS/USDT","IRYS"), ("ASTERUSDT","ASTER/USDT","ASTER"),
    ("PENGUUSDT","PENGU/USDT","PENGU"), ("EPICUSDT","EPIC/USDT","EPIC"),
    ("HOMEUSDT","HOME/USDT","HOME"),
]
